### ISSUE TITLE
odom_model_type support for car-like model in amcl

### ISSUE THREAD

**Issue by r91andersson** [ros-planning/navigation#1086]
Is there any support in amcl when using a car-like robot model (using ackermann steering)?
I saw that the odom_model_type only supports differential and omni based models.

We're are today using TEB local planner with our car-like robot model when we're running outdoor(with GPS) navigation, but now we want to run indoor, so instead of GPS we have added a lidar scanner on the robot, so then it makes more sense to use AMCL for the indoor navigation. So is this car-like model supported in AMCL? (As it is in the TEB)

**Comment by mikeferguson** [comment]
There is not a specific Ackermann model in AMCL. That said, the diff model will probably work for you - since your odometry will pretty much encode the possible motion of the car and AMCL diff model will simply add noise to the distance/rotation reported.

I'd suggest posting further questions related to this setup to answers.ros.org - there are a lot more active users there and it is the preferred venue for asking questions.
