### ISSUE TITLE
Using Navigation Stack together with Moveit

### ISSUE THREAD

**Issue by adamanov** [ros-planning/navigation#1203]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Melodic|
* OS Version: e.g. Ubuntu 18.04
* Robots: Clearpath Jackal mobile platform  + OpenMANIPULATOR-P (RM-P60-RNH)

### Steps to reproduce
I create a combined URDF model for both robot, where Arm placed on the Jackal mobile platform. After that used Moveit Asistant setup, and created a combined moveit_config file for URDF model 
![image](https://user-images.githubusercontent.com/53511072/174647381-344a230d-b4d0-459a-a2e2-84e23f7d7388.png)

### Expected behavior
By launching both `move_group.launch` (from moveit) and `move_base.launch` (from navigation stack) I expected to drive with jackal to the destination point and after that use moveit to pick a certain object. 

### Actual behavior
The robot platform does not move after setting a Goal position from Rviz, however, I can still move the robot arm within moveit rviz window.

I assume that the problem is related to the controller of both robots. But I am not sure if both frameworks can be used together on the single robot (mobile platform with robot arm)

### Question
Is it possible to use both frameworks together? or How can I control both the mobile platforms and arm robots with Rviz? for a future task in gazebo environment?

**Comment by mikeferguson** [comment]
There are certainly many people using both systems together (the biggest challenge is usually that you often need to set the moveit planning frame to base_link since otherwise things like an octomap get really big - and thus usage is usually "drive to a location with nav and then manipulate from a fixed base pose"). I'd suggest posting to answers.ros.org with more details about your setup in order to debug what is wrong.
