### ISSUE TITLE
DWA, TEB and DWB can not control with low acceleration 

### ISSUE THREAD

**Issue by artelrobotics** [ros-planning/navigation#1223]
Hi everyone , Does anyone has experience of using DWA, Base , DWB, TEB local planner?
I am having trouble with DWA, TEB and DWB. My robot has big footprint and we use slow acceleration in order to have better performance. However when we use DWA, TEB it can not control and it is occilating around global plan like snake motion. Could anyone can help.
I have calculated my robot acceleration and it was linear 0.08 m/s2  and angular 0.15 rad/s2.
When I configured with this parameters , robot giving high linear vel and low angular due to this it can not follow global plan.
Only Base local planner works normally but i need backward motion as well

**Comment by mikeferguson** [comment]
DWA/DWB generally struggle with low acceleration limits since they end up sampling a very small velocity region. In general, I stick with trajectory rollout (base local planner) when I have a robot with very low acceleration limits.

In general, I would recommend posting to answers.ros.org for things like this - there is a much larger community there to respond
