### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by rctoris** [ros-planning/navigation#194]
Any chance of releasing into indigo anytime soon?

**Comment by mikeferguson** [comment]
Yes, sometime in the next week probably. The last dependency was BFL, which just made it into debs.

**Comment by mikeferguson** [comment]
Just an update -- I'll be releasing this as soon as the buildfarm optimization issues are worked out (https://github.com/ros-infrastructure/buildfarm/issues/197), since I imagine that nav will perform as poorly as moveit does.

@DLu given that there are no API-breaking changes that I see on the horizon, and we'd like to keep the maintenance overhead low, I think we'll not branch indigo-devel for now, and just continue releasing the 1.11 branch into both hydro and indigo until we have a compelling reason to branch.

**Comment by DLu** [comment]
+1 to not branching.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/4412
