### ISSUE TITLE
Get Rid of footprint_layer

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#289]
Originally, the footprint clearing was done in its own layer, since it was a different kind of functionality than adding/clearing obstacles. 

However, having the footprint clearing in its own layer does not permanently remove the obstacle, which means that when the footprint moves, the obstacles reappear. 

This was temporarily fixed in 0e544b1276f26a8e96f0613a53103a136f11d957, but should be changed so it doesn't create the weird layer namespaces.

**Comment by skaynama** [comment]
Is permanently clearing the obstacle necessarily a good solution? I'm just thinking what if the robot rolls over the inflated obstacle (e.g. due to cross track or localization error). Having the footprint layer temporarily clear the obstacle makes sense because otherwise the robot's position would be invalid and any attempt to replan using common planners would fail (bad initial condition). Removing the obstacle permanently in this case is obviously wrong and undesirable. What are your thoughts?

**Comment by DLu** [comment]
The use case for the footprint layer is for imperfect sensor filtering of the robot itself. If your sensor happens to see a lethal obstacle within its footprint (such as its own hand, perhaps) then all resulting trajectories will be invalid because they will collide with that point. 

The inflation layer is handled AFTER the obstacle layer (and the footprint clearing), thus the inflated obstacle will not be removed. 

The motivation of removing the lethal points from the obstacle layer's costmap and not just the master costmap is so that when the robot moves to a new location, the imperfectly sensed point on the robot will not still be there.

**Comment by skaynama** [comment]
What if the obstacle was a legitimate obstacle but it was sensed only because of bad localization (the robot thought an obstacle is within its footprint because the robot's position estimate had error). Say we clear that obstacle permanently, and move away and regain perfect localization. Then there would be a gap in place of the legitimate obstacle -- which is clearly undesirable. How would this scenario be handled?

**Comment by DLu** [comment]
That's a plausible enough scenario. The gap would probably get filled in again though when it was resensed. And there's still a flag and plenty of other ways to customize the behavior if this sort of behavior doesn't work for you. This issue is primarily about getting rid of the footprint_layer object.
