### ISSUE TITLE
Possible bug with Odometry message

### ISSUE THREAD

**Issue by ziyangli** [ros-planning/navigation#303]
Dear all,

I am publishing Odometry at 200Hz and I use `throttle` to republish at 100Hz, however I only get 25Hz result. I have tested a few other message types and only find this problem with Odometry. Please check the following link for the issue detail.

https://github.com/ros/ros_comm/issues/560

**Comment by mikeferguson** [comment]
Odometry is a big message (due to the covariance matrices), which might be the cause of this. However, the navigation stack has no control over the generation of messages, nor the shape_shifter class used inside topic tools, nor even the Odometry message (that is actually part of nav_msgs, which is in the ros/common_msgs repo).
