### ISSUE TITLE
'move_base_msgs/MoveBaseAction.h' file not found

### ISSUE THREAD

**Issue by zurish** [ros-planning/navigation#319]
Hi there. I was trying to install navigation stack to indigo and cloned it from this repository but I did not notice that the branch is jade. Then I used the command:
`./src/catkin/bin/catkin_make_isolated --from-pkg move_base --install -DCMAKE_BUILD_TYPE=Release` 
in my workspace. There was a error: 
`'move_base_msgs/MoveBaseAction.h' file not found`
I found that in the navigation repository for indigo there is a folder named `move_base_msgs` but `MoveBaseAction.h` does not exist. Even so, I manually copied it to my own navigation stack. But when I run the same command above, the same error occurred. How can I solve this problem? Thank you.

**Comment by mikeferguson** [comment]
that would be a generated header, have you built move_base_msgs? I'm not entirely familiar with catkin_make_isolated and  how it builds dependencies.

Also, this question is probably better suited for answers.ros.org -- as navigation is building fine on the buildfarm and so the issue is likely with your particular setup rather than a bug in navigation.
