### ISSUE TITLE
Origin does not update on local costmap

### ISSUE THREAD

**Issue by kayak0806** [ros-planning/navigation#401]
When running a custom costmap layer in the local costmap, the costmap origin is never updated. This causes the `worldtomap` function to return coordinates relative to (0,0) instead of the robot's position. the `setCost` function does seem to work properly, resulting in a costmap layer that sees things near the origin and prints them near the robot. 
Other layers in the local costmap (an Obstacle layer and an Inflation layer) are working fine and `rolling_window` is set to true.

**Comment by mikeferguson** [comment]
there isn't enough information here to even begin debugging this -- you haven't even said which "custom costmap layer" -- and if the other layers are working fine, then the issue is in the "custom costmap layer"

You are likely failing to update your bounds in the custom layer -- but we can't fix that upstream. See https://github.com/ros-planning/navigation/blob/jade-devel/costmap_2d/plugins/obstacle_layer.cpp#L344
