### ISSUE TITLE
Is there any reason the navigation packages has been strongly coupled to each other?

### ISSUE THREAD

**Issue by DaikiMaekawa** [ros-planning/navigation#420]
I wonder why Navigation Stack provides each navigation packages under such the condition implementing as a plugin into move_base. My first guess, that's why it has the advantage of resources. Let me know why you made the navigation system like this instead of using nodelets for communicating ROS messages.

**Comment by mikeferguson** [comment]
I'm pretty sure move_base predates nodelets. Even if nodelets were around, I think this is still a case where a C++ API makes sense, you have modules providing function calls at very high rates (local planner/controller gets called at 30-50hz typically). Further, things like the costmaps have to be C++ API, because the API is so complex -- you'd have dozen of actions to replicate it.
