### ISSUE TITLE
move_base feedback status not update after TrajectoryROS finish planning

### ISSUE THREAD

**Issue by willdzeng** [ros-planning/navigation#489]
I am having problem of move_base not changing the status. Seems like move_base didn't update the feedback status instead it's publishing the goal reached in the result topic. Also It doesn't make sense to not printing a goal reached after it reaches the goal.

I am using the new jade-devel branch.

For example, when the planning finished. I got this feedback as my last feedback.

> header: 
>   seq: 1256
>   stamp: 
>     secs: 1467060002
>     nsecs: 881650134
>   frame_id: ''
> status: 
>   goal_id: 
>     stamp: 
>       secs: 1467059923
>       nsecs: 881423990
>     id: /planner/move_base-3-1467059923.881423990
>   status: 1
>   text: This goal has been accepted by the simple action server
> feedback: 
>   base_position: 
>     header: 
>       seq: 0
>       stamp: 
>         secs: 1467060002
>         nsecs: 721923983
>       frame_id: map
>     pose: 
>       position: 
>         x: 3.13044031998
>         y: 0.112499842441
>         z: 0.0
>       orientation: 
>         x: 0.0
>         y: 0.0
>         z: 0.0534534682742
>         w: 0.998570341403

But I do get a result callback of result topic. I think it make sense to update the feedback topic also, so that we don't need to subscribe two topic.

**Comment by mikeferguson** [comment]
move_base is intended to be used with actionlib -- it provides an action interface -- rather than thinking about this as different topics, you probably want to be using the actionlib interface which will tell you if the goal request succeeded/preempted/failed/etc.

The feedback is really just a convenience -- the same data is actually available by checking your base_link -> map (or equivalent) transform using TF.

Unfortunately, adding different feedback/result would change the definition of the message, breaking the MD5 checksum, which really isn't acceptable as the whole navigation stack is version > 1.0.
