### ISSUE TITLE
return value of map_calc_range

### ISSUE THREAD

**Issue by qh-huang** [ros-planning/navigation#515]
in file `amcl/src/map/map_range.cpp`, function `double map_calc_range(map_t *map, double ox, double oy, double oa, double max_range)`

```
...(ignored)
  x = x0;
  y = y0;

  if(x0 < x1)
    xstep = 1;
  else
    xstep = -1;
  if(y0 < y1)
    ystep = 1;
  else
    ystep = -1;

  if(steep)
  {
    if(!MAP_VALID(map,y,x) || map->cells[MAP_INDEX(map,y,x)].occ_state > -1)
      return sqrt((x-x0)*(x-x0) + (y-y0)*(y-y0)) * map->scale;
  }
  else
  {
    if(!MAP_VALID(map,x,y) || map->cells[MAP_INDEX(map,x,y)].occ_state > -1)
      return sqrt((x-x0)*(x-x0) + (y-y0)*(y-y0)) * map->scale;
  }
```

x, y are not changed after assigned value of x0 and y0.
if the cell is unknown or occupied (occ_state > -1), the return value will always be 0.

It makes no sense, or do I miss anything?

Thanks a lot!

**Comment by mikeferguson** [comment]
I think what has happened here is that someone just copied the same lines below (inside the while loop, after the step has been applied). The value of 0 is correct (the range is zero since the starting box is occupied) and the compiler is probably smart enough to optimize out the maths, so there is no computation penalty. I'm going to close this issue, since it's not really a big deal.

If you're inclined to make the code prettier, please open a PR against the lunar branch.
