### ISSUE TITLE
move_base action server should provide goal failure reason

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#57]
so client can react accordingly. I typically experience three kinds of failures. I didn't check the code, but I suppose there're some others:
- Oscillation timeout many times happen because the robot is physically blocked
- Plan failed, as a valid plan cannot be found
- Controller failed, as a safe velocity command cannot be found

**Comment by hershwg** [comment]
This information is actually already available.  After you see that the goal has failed, call
[SimpleActionClient::getState()](http://ros.org/doc/groovy/api/actionlib/html/classactionlib_1_1SimpleActionClient.html#a6a2baa3674db5ab9b187783371209bd3) and then on the resulting [SimpleClientGoalState object](http://ros.org/doc/groovy/api/actionlib/html/classactionlib_1_1SimpleClientGoalState.html) call getText().

The resulting text string should be either:
`Failed to find a valid control. Even after executing recovery behaviors.` or
`Failed to find a valid plan. Even after executing recovery behaviors.` or
`Robot is oscillating. Even after executing recovery behaviors.`.

I'm not saying this is a great API, but it does provide what you are asking for.

Do you think we should instead chang MoveBase.action to have an enum in the result indicating more tersely what the reason was?

**Comment by corot** [comment]
Agggh...  stupid me; how I missed that point? As there are no result definition on .action file, I assumed there was no specific result information. Sorry.

Well, an enum value would be easier to use, but as it's not necessary, I would postpone the change in action file until a more important change is required. Keep this issue open as a reminder, if you want.

**Comment by corot** [comment]
The general idea goes on in issue #484. Closing this
