### ISSUE TITLE
Will the parameter padded_footprint_ in  costmap_2d_ros.cpp be changed with the cycle?

### ISSUE THREAD

**Issue by pengjiawei** [ros-planning/navigation#626]
in costmap_2d_ros.cpp,when we call the function updateMap(),it will publish the footprint with the cycle,and then,we will always call the funtcion setUnpaddedRobotFootprintPolygon().is that right?

and I found that the parameter padded_footprint_ will be increase with the cycle under the influence of the function transformFootprint() in footprint.cpp and the function setUnpaddedRobotFootprint() in costmap_2d_ros.cpp.am I wrong?

I actually don't know why we need to transform footprint

**Comment by mikeferguson** [comment]
The published footprint is just for debugging -- makes it possible to see where the robot is when overlayed on the cost map in RVIZ. Likely, the reason to transform the footprint within that function is so that the display of the costmap and the display of the footprint will be consistent with where the frames are at that point (technically, you could publish footprint in the robot local frame, and let RVIZ do the transform, but it may end up with a different result if there is anything wonky going on with TF, etc).

The "transformFootprint()" function takes the actual padded_footprint_ as const, so it does not change it.
