### ISSUE TITLE
move_base doesn't accept goals in frames other than the map frame

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#7]
[Originally posted by ben cohen in kforge trac]

move_base likes getting its goals in the map frame(from /move_base_simple/goal) and that's very understandable. It won't plan to a goal in any frame on the robot and I don't think it will output some sort of roserr that can be viewed in rxconsole either. 

I agree that your normal user would want to send a goal in the map frame but the only reason why I'm filing this ticket is because if a user is trying to set a "2DNav Goal" for their robot in rviz but the fixed frame is in a robot frame, then the user will be left wondering 'why isn't my robot moving?'. There won't be any negative feedback other than the robot isn't moving and if they have the proper visualizations displayed, then no path will be drawn.

I know that it would be very nice if rviz gave the user more feedback but I don't see why, the move_base simple action server can't just use TF to transform the goal into the map frame upon receiving it. 

It's just a thought. I have a feeling this was brought up earlier but shot down for a reason that I'm not aware of.

**Comment by corot** [comment]
This issue has been implemented, isn't it? Method MoveBase::goalToGlobalFrame should do it.

However, I have found some situations in which I would like to make a plan relative to the goal frame, instead of converting it to global frame:
- Use move_base just for obstacle avoidance
- Use move_base for final approach to a target at view (an [alvar marker](http://www.ros.org/wiki/ar_track_alvar))

I wonder if this can be an useful feature for more people...

**Comment by hershwg** [comment]
@corot is correct, this is already implemented in goalToGlobalFrame().

I just tested this and I can give the robot a goal while rviz's "fixed frame" is /base_link, and it works fine.  The only thing weird is that having /base_link as the "fixed frame" means that the robot does not appear to move in rviz, instead the rest of the world around it moves.
